name: Create and push Docker build image
on:
  push:
    branches: [ main ]
  tags: [ 'v*.*.*' ]
# TODO: remove this once testing completed
  pull_request:
    branches: [ main ]

jobs:
  public_docker_image:
    name: Publish Docker image to Github Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mkst
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push to Github registry (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push to Github registry (versioned)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
