name: CI
on: [push, pull_request]
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y file unzip wget

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build --target export --output build .

      - name: Test
        run: |
          wget https://cdn.discordapp.com/attachments/727918646525165659/1129759991696457728/GC_WII_COMPILERS.zip
          unzip GC_WII_COMPILERS.zip
          MWCIncludes=. build/wibo GC/2.7/mwcceppc.exe -c test/test.c -Itest
          file test.o

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: wibo
          path: build/wibo

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/wibo
