name: CI
on: [push, pull_request]
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: actions/checkout@v2

      - name: Install GCC multilib
        run: |
          apt-get update
          apt-get install -y cmake file gcc-multilib g++-multilib unzip wget

      - name: Configure
        # Replace with RelWithDebInfo when -O2 crash is fixed
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          wget https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip
          unzip GC_WII_COMPILERS.zip
          MWCIncludes=. build/wibo GC/2.7/mwcceppc.exe -c test/test.c -Itest
          file test.o

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: wibo
          path: build/wibo

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/wibo
